/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Backtests */
        post: operations["backtests_backtests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Candles */
        get: operations["candles_candles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Client Event */
        post: operations["client_event_client_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Symbols */
        get: operations["symbols_symbols_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timeframes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Timeframes */
        get: operations["timeframes_timeframes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BacktestRequest */
        BacktestRequest: {
            /**
             * Fees
             * @default 0
             */
            fees: number;
            /**
             * Initial Cash
             * @default 10000
             */
            initial_cash: number;
            /**
             * Limit
             * @default 5000
             */
            limit: number;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            /**
             * Slippage
             * @default 0
             */
            slippage: number;
            /** Strategy */
            strategy: string;
            /** Symbol */
            symbol: string;
            /**
             * Timeframe
             * @default 1m
             */
            timeframe: string;
        };
        /** BacktestResponse */
        BacktestResponse: {
            /** Candle Count */
            candle_count: number;
            /** Final Value */
            final_value: number;
            /** Initial Cash */
            initial_cash: number;
            /** Max Drawdown */
            max_drawdown: number;
            /** Sharpe Ratio */
            sharpe_ratio: number | null;
            /** Strategy */
            strategy: string;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
            /** Total Return */
            total_return: number;
            /** Total Trades */
            total_trades: number;
        };
        /** Candle */
        Candle: {
            /** Open */
            OPEN: number;
            /** Close */
            close: number;
            /**
             * Datetime
             * Format: date-time
             */
            datetime: string;
            /**
             * Fecha Carga
             * Format: date-time
             */
            fecha_carga: string;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Origen */
            origen: string;
            /** Spread */
            spread: number;
            /** Symbol */
            symbol: string;
            /** Tickvol */
            tickvol: number;
            /** Volume */
            volume: number;
        };
        /** CandleWindow */
        CandleWindow: {
            /** Candles */
            candles: components["schemas"]["Candle"][];
            /** Has More */
            has_more: boolean;
            /** Next Cursor */
            next_cursor: string | null;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
        };
        /** ClientEvent */
        ClientEvent: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "api_failure" | "unhandled_error" | "unhandled_rejection";
            /** Message */
            message: string;
            /** Path */
            path: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvalidStrategyParameters */
        InvalidStrategyParameters: {
            /** Detail */
            detail: string;
            /** Strategy */
            strategy: string;
            /** Title */
            title: string;
            /**
             * Type
             * @constant
             */
            type: "invalid_strategy_parameters";
        };
        /** ServiceUnavailable */
        ServiceUnavailable: {
            /** Detail */
            detail: string;
            /** Title */
            title: string;
            /**
             * Type
             * @constant
             */
            type: "service_unavailable";
        };
        /** SymbolCatalog */
        SymbolCatalog: {
            /** Symbols */
            symbols: string[];
        };
        /** UnsupportedStrategy */
        UnsupportedStrategy: {
            /** Detail */
            detail: string;
            /** Strategy */
            strategy: string;
            /** Title */
            title: string;
            /**
             * Type
             * @constant
             */
            type: "unsupported_strategy";
        };
        /** UnsupportedSymbol */
        UnsupportedSymbol: {
            /** Detail */
            detail: string;
            /** Symbol */
            symbol: string | null;
            /** Title */
            title: string;
            /**
             * Type
             * @constant
             */
            type: "unsupported_symbol";
        };
        /** UnsupportedTimeframe */
        UnsupportedTimeframe: {
            /** Detail */
            detail: string;
            /** Timeframe */
            timeframe: string;
            /** Title */
            title: string;
            /**
             * Type
             * @constant
             */
            type: "unsupported_timeframe";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    backtests_backtests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
            /** @description The requested analysis inputs are not supported. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnsupportedSymbol"] | components["schemas"]["UnsupportedTimeframe"] | components["schemas"]["UnsupportedStrategy"] | components["schemas"]["InvalidStrategyParameters"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The market source cannot be read. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceUnavailable"];
                };
            };
        };
    };
    candles_candles_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                timeframe?: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandleWindow"];
                };
            };
            /** @description The requested symbol or timeframe is not supported by this candle slice. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnsupportedSymbol"] | components["schemas"]["UnsupportedTimeframe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The market source cannot be read. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceUnavailable"];
                };
            };
        };
    };
    client_event_client_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    symbols_symbols_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolCatalog"];
                };
            };
            /** @description The market symbol catalog cannot be read from the source. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceUnavailable"];
                };
            };
        };
    };
    timeframes_timeframes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
}
